package com.orange.sqlexecutor.dao;

import com.orange.sqlexecutor.entity.DBInfo;

import java.util.List;

public interface DBInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    int insert(DBInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    int insertSelective(DBInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    DBInfo selectByPrimaryKey(Integer dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBInfo record);

    /**
     * 获取全部数据源列表
     *
     * @return
     */
    List<DBInfo> selectAll();
}