package com.orange.sqlexecutor.entity;

public class DBInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.DB_ID
     *
     * @mbggenerated
     */
    private Integer dbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.DB_NAME
     *
     * @mbggenerated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.DB_URL
     *
     * @mbggenerated
     */
    private String dbUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.DB_TYPE
     *
     * @mbggenerated
     */
    private String dbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_INFO.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    private Integer status = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.DB_ID
     *
     * @return the value of DB_INFO.DB_ID
     *
     * @mbggenerated
     */
    public Integer getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.DB_ID
     *
     * @param dbId the value for DB_INFO.DB_ID
     *
     * @mbggenerated
     */
    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.DB_NAME
     *
     * @return the value of DB_INFO.DB_NAME
     *
     * @mbggenerated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.DB_NAME
     *
     * @param dbName the value for DB_INFO.DB_NAME
     *
     * @mbggenerated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.DB_URL
     *
     * @return the value of DB_INFO.DB_URL
     *
     * @mbggenerated
     */
    public String getDbUrl() {
        return dbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.DB_URL
     *
     * @param dbUrl the value for DB_INFO.DB_URL
     *
     * @mbggenerated
     */
    public void setDbUrl(String dbUrl) {
        this.dbUrl = dbUrl == null ? null : dbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.DB_TYPE
     *
     * @return the value of DB_INFO.DB_TYPE
     *
     * @mbggenerated
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.DB_TYPE
     *
     * @param dbType the value for DB_INFO.DB_TYPE
     *
     * @mbggenerated
     */
    public void setDbType(String dbType) {
        this.dbType = dbType == null ? null : dbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.USER_NAME
     *
     * @return the value of DB_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.USER_NAME
     *
     * @param userName the value for DB_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_INFO.PASSWORD
     *
     * @return the value of DB_INFO.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_INFO.PASSWORD
     *
     * @param password the value for DB_INFO.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}